### ISSUE TITLE
MALDI Pyramids Look Odd at Low Resolution Levels

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/ingest-pipeline#108]
If you look at the lower resolution levels, it looks like something went wrong with the downsampling, where there are these stripes:
<img width="581" alt="Screen Shot 2020-07-18 at 6 50 37 PM" src="https://user-images.githubusercontent.com/43999641/87950193-f8f45280-ca74-11ea-82cf-d315acfaa6b8.png">
<img width="551" alt="Screen Shot 2020-07-18 at 6 50 09 PM" src="https://user-images.githubusercontent.com/43999641/87950197-f98ce900-ca74-11ea-8618-c09b65871d1a.png">

This could be an issue with the data being 32 bit float (I still don't understand why it has to be this data type) or this could be something else.  Perhaps the pyramid generator relying just on dropout and not a gaussian filter + dropout is biting us.  I have no insight  on to this one - if it is a real issue, and we can reproduce it, I would just report it to glencoe.
 
I have confirmed this using Fiji (i.e not just our image viewer).

Here are the UUIDs:

```
PROD: 146063814f6bd2b6546e950d0ca5f8c3,HBM645.ZQSN.258,['MALDI-IMS-neg'],Vanderbilt TMC
TEST: 71f6fe348843c65e3af47388d181c0e6,HBM587.HGDH.925,['MALDI-IMS-neg'],IEC Testing
```

**Comment by ilan-gold** [comment]
One option is to just not run the pyramid pipeline on the IMS images.

**Comment by icaoberg** [comment]
@ilan-gold recreated results so you can take a look at the logs on TEST `IEC Testing Group/097358f1cb26c275adbeabfe4ceca8a9/`
