### ISSUE TITLE
mxIF Images Have no Channel Names

### ISSUE THREAD

**Issue by ilan-gold** [hubmapconsortium/ingest-pipeline#112]
@icaoberg  is looking into this, but I downloaded a dataset he ran on dev and when I looked at the channel names, they were all of the form `C01` `C02` etc.  I am not sure if this is intentional from Vanderbilt (which would be require a resolution and some buy-in from interested parties) or a bug in our pipelines.

Here is the globus URL:

https://app.globus.org/file-manager?origin_id=0ecd3ce8-bf32-4d64-9405-4ebbcbfff116&origin_path=%2FIEC%20Testing%20Group%2F63a81b0b44677182327c108ef5df7c9e%2Foutput_offsets%2FprocessedMicroscopy%2FVAN0008-RK-403-101-MxIF_cyc1_images%2F

**Comment by icaoberg** [comment]
@ilan-gold looking at a sample image from the ingested dataset

```
~/bin/bftools/tiffcomment VAN0003-LK-32-22-MxIF_cyc1_registered.ome.tiff | ~/bin/bftools/xmlindent

<?xml version="1.0" encoding="UTF-8"?>
<ome:OME xmlns:ome="http://www.openmicroscopy.org/Schemas/OME/2016-06" xmlns:sa="http://www.openmicroscopy.org/Schemas/sa/2013-06s" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06 http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd">
   <ome:Image ID="Image:0" Name="default.png">
      <ome:AcquisitionDate>
         2019-12-18T16:09:01.121779
      </ome:AcquisitionDate>
      <ome:Pixels BigEndian="false" DimensionOrder="XYCTZ" ID="Pixels:0" Interleaved="false" PhysicalSizeX="0.5" PhysicalSizeXUnit="µm" PhysicalSizeY="0.5" PhysicalSizeYUnit="µm" SizeC="4" SizeT="1" SizeX="41500" SizeY="41220" SizeZ="1" Type="uint16">
         <ome:Channel ID="Channel:0:0" Name="C01" SamplesPerPixel="1">
            <ome:LightPath />
         </ome:Channel>
         <ome:Channel ID="Channel:1:0" Name="C02" SamplesPerPixel="1" />
         <ome:Channel ID="Channel:2:0" Name="C03" SamplesPerPixel="1" />
         <ome:Channel ID="Channel:3:0" Name="C04" SamplesPerPixel="1" />
      </ome:Pixels>
   </ome:Image>
   <sa:StructuredAnnotations />
</ome:OME>
```

The channel names `C0`, etc. are the names used in the pre-processed images.

**Comment by ilan-gold** [comment]
@icaoberg Thanks for checking.  That doesn't seem like great news, but thanks for checking.  We should bring this up at 1.
