### ISSUE TITLE
Split data submissions with multiple datasets sharing the same UUID

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-pipeline#114]
The following data submissions had multiple datasets that were submitted under the same UUID:

STAN bulkATAC
STAN metabolomics
STAN proteomics
UCSD SNARE-RNAseq
UCSD SNARE-AC
UFLA IMC

UCSD SNARE-AC has been fixed. The remaining data submissions need the following done to them:

1. Metadata.tsv updated with list of files that pertain to each row of the TSV (a single dataset)
2. Metadata.tsv updated with updated and newly created dataset names for each dataset.
3. Creation of new UUIDs and renaming or naming of datasets based on updated metadata.tsv
4. Creation and execution of a script to move files to new UUID directories
5. Update metadata.tsv to remove extra information (filenames and dataset names)
6. Distribute files containing one row of metadata.tsv to their corresponding UUID directories.

**Comment by jswelling** [comment]
Done by @pdblood
