### ISSUE TITLE
Create a diagram that shows the communication steps that implement a data ingest operation

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-pipeline#14]
Phil will put his talk and Nick's poster in HIVE-IEC-PSC Google Drive folder:

https://drive.google.com/drive/folders/15cP8zziUKF7kvQHPEnDZf1wHpV7ZsxNe

**Comment by jswelling** [comment]
Collect all these diagrams in @pdblood 's space on google drive.

**Comment by mccalluc** [comment]
Should https://docs.google.com/drawings/d/1Cicn-JUVU9QmfsP0CHtGPJkqCe08DlENlKR02leOiLg/edit point to this, for people that want more details about what happens behind the scenes?

**Comment by khanshawPSC** [comment]
Complete
