### ISSUE TITLE
Links to CWL files on GitHub and in CWL Viewer broken due to inconsistent provenance information

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/ingest-pipeline#143]
### Incorrect Analysis Provenance 

See e.g. https://portal.hubmapconsortium.org/browse/dataset/e923d09c0f0b7a0da4d53695e1b167f6 (HBM544.VKZP.647):

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/1216518/90895929-d4034000-e390-11ea-8039-4ba512d90702.png">

Corresponding JSON in https://portal.hubmapconsortium.org/browse/dataset/e923d09c0f0b7a0da4d53695e1b167f6.json (see `metadata` > `dag_provenance_list`):

<img width="684" alt="image" src="https://user-images.githubusercontent.com/1216518/90895726-92729500-e390-11ea-8d8f-d29a60d66d98.png">

### Correct Analysis Provenance

See e.g. https://portal.hubmapconsortium.org/browse/dataset/b759f38c3dbf63b8392af961b429b733 (HBM669.QPPZ.938):

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/1216518/90896996-8687d280-e392-11ea-85ce-86780a9796c3.png">

Corresponding JSON in https://portal.hubmapconsortium.org/browse/dataset/b759f38c3dbf63b8392af961b429b733.json (see `metadata` > `dag_provenance_list`):

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1216518/90897298-ed0cf080-e392-11ea-966a-58d105166eda.png">

**Comment by jswelling** [comment]
Fixed in ingest-pipeline e4f255d
