### ISSUE TITLE
Complete security review and update of Airflow deployments.

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-pipeline#161]
Document and implement Airflow security best practices. See infrastructure Google Doc.

**Comment by khanshawPSC** [comment]
GLOBUS Auth on Airlflow

PB: Bring in Security Team to review the protocols

**Comment by khanshawPSC** [comment]
Moved to a Systems Asana task: https://app.asana.com/0/1138475663201890/1200246916310467/f
