### ISSUE TITLE
LC-MS assay_types

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-pipeline#164]
@mccalluc @ngehlenborg 
There are 4 assay_types of LC-MS assays and 6 omics types (proteomics, lipidomics & metabolomics - targeted & untargeted for each) that can be interrogated with any of these 4 assays. 
I realized we can simply use the **"is_targeted"** field and the '**analyte_class**" fields to accommodate all 6 omics types.

**assay types:**
label-free LC-MS
Labeled LC-MS
Label-free LC-MS/MS
Labeled LC-MS/MS

**Omics types = is_targeted” + “analyte_class”:**
Untargeted proteomics
Targeted proteomics 
Untargeted metabolomics
Targeted metabolomics
Untargeted lipidomics
Targeted lipidomics

**Comment by khanshawPSC** [comment]
@cebriggs7135 I do not think this belongs in ingest-pipeline.

**Comment by cebriggs7135** [comment]
@khanshawPSC This is a year old and moot at this point. We can close this.
