### ISSUE TITLE
Create a second HIVE VM to run ingest-api for PROD instance of Portal

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-pipeline#171]
Explore deploying on a HuBMAP DTN outside PSC firewall.
Phil pursue with Kathy, Shane, and Derek.
Bill and Zhou for connecting to AWS.

**Comment by khanshawPSC** [comment]
Moved to the Systems Asana board: https://app.asana.com/0/1138475663201890/1200306857466675/f
