### ISSUE TITLE
Create subtasks for the *Initiate support for intra-consortium user workflows* milestone

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/ingest-pipeline#181]
Enable Globus authentication to the Airflow interface to facilitate execution of workflows by authenticated HIVE developers.
**Completion criteria:** HIVE developers can authenticate to the Airflow interface using Globus. 
Document the HuBMAP hybrid-cloud workflow architecture on the HuBMAP collaboration portal. 
Develop a plan to support intra-consortium user workflows (e.g. containerized workflows submitted by HIVE and TMC members via Airflow) on the HIVE infrastructure on HuBMAP data.
#Q2 #YR3Request

https://app.asana.com/0/1145417635427233/1183567545222036/f

**Comment by jpuerto-psc** [comment]
Subtasks for project:

Complete development environment setup
Investigate Globus authentication
Investigate Airflow plugin setup
Design Globus authentication plugin for Airflow
Implement Globus authentication plugin for Airflow

**Comment by khanshawPSC** [comment]
Subtasks added to Asana and assigned to Juan.
