### ISSUE TITLE
Create Subtasks for Expand support for user workflows

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/ingest-pipeline#184]
●       Establish robust integration of Airflow with GitHub and Dockstore, along with best practices for deploying workflows on the HIVE infrastructure.
**Completion criteria**: Consortium users’ workflows hosted in GitHub and/or Dockstore, including TMC pipelines, can be executed on the HIVE infrastructure.
●       Revise and expand documentation of the HuBMAP architecture to reflect additions.
●       Develop a plan to support external user workflows on HuBMAP data.
Due Date: Dec 18, 2020
Tags: Q2, Year 3 Request

https://app.asana.com/0/1145417635427233/1198190677387206/f

**Comment by khanshawPSC** [comment]
This has been moved back to Q3

**Comment by jswelling** [comment]
Some possible sub-tasks:
* Define the contact points between the user workflow and the surrounding software infrastructure.  For example, existing workflows are initiated by a bash command providing a very limited set of input parameters (data directory, scratch directory, assay/workflow name, etc).
* Define the necessary metadata returned by the workflow and the methods by which it is returned.  For example, current workflows give some information about output files and QA information.
* Define what output is to be saved from the workflow.  For example, a JSON document might define the expected output directory structure.
* Produce an Airflow DAG to encapsulate a generic workflow with this interface.
* Test on a user workflow, including providing the necessary support to allow the user to modify their workflow to match the defined contact points.

**Comment by khanshawPSC** [comment]
Joel provided subtasks
