### ISSUE TITLE
Sample Id to files mapping

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-pipeline#20]
When sending metadata information back to the Ingest System from Airflow send back a mapping of tissue ids (in Vanderbilt data ids of slices)  to files.

**Comment by pdblood** [comment]
@shirey @jswelling: Is this issue still relevant?

**Comment by jswelling** [comment]
Need clarification from @shirey : is this still relevant?  What does it look like in the provenance tree?

**Comment by shirey** [comment]
@jswelling @pdblood No, I don't think this is needed any longer.  May bring up similar issues during the "Data Submission" reorg.  I'll close now.
