### ISSUE TITLE
Investigate Airflow plugin setup

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/ingest-pipeline#217]
https://app.asana.com/0/0/1199588373289887/f

Milestone: Initiate support for intraconsortium user workflows
Enable Globus authentication to the Airflow interface to facilitate execution of workflows by authenticated HIVE developers.
Completion criteria: HIVE developers can authenticate to the Airflow interface using Globus. 
Document the HuBMAP hybrid-cloud workflow architecture on the HuBMAP collaboration portal. 
Develop a plan to support intraconsortium user workflows (e.g. containerized workflows submitted by HIVE and TMC members via Airflow) on the HIVE infrastructure on HuBMAP data.

**Comment by jpuerto-psc** [comment]
This has been completed.
