### ISSUE TITLE
Add log-out functionality to Airflow UI

### ISSUE THREAD

**Issue by jpuerto-psc** [hubmapconsortium/ingest-pipeline#223]

**Comment by khanshawPSC** [comment]
https://app.asana.com/0/0/1199896111728103/f

Asana task: GLOBUS authentication component enhancements

**Comment by jpuerto-psc** [comment]
To implement this, we will have to add our own log-out button. Airflow does not allow for custom logout routines to be implemented. Therefore, the logout button that they provide cannot be used.

![image](https://user-images.githubusercontent.com/68066250/120852411-2ab8bf80-c548-11eb-92ac-6c8f7df44835.png)

This is how users will have to log-out.

**Comment by jpuerto-psc** [comment]
PR #335 includes this functionality.
