### ISSUE TITLE
Ingest Stanford CODEX datasets

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/ingest-pipeline#293]

**Comment by jswelling** [comment]
As of April 9, awaiting updates to CODEX directory schema to support Stanford and possible updates to memory allocation in the sprm component of the CODEX workflow.

**Comment by jswelling** [comment]
Awaiting CODEX directory schema which supports Stanford format; awaiting https://github.com/hubmapconsortium/sprm/issues/10
