### ISSUE TITLE
Add the ome-tiff tiler to the CODEX workflow

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/ingest-pipeline#302]

**Comment by jswelling** [comment]
Ilan says this should happen just before the offsets calculation.  He asks that the segmentation mask also be run through pyramid generation if possible.

There is a small sample CODEX dataset (for short test runs) in /hive/hubmap/data/CMU_Tools_Testing_Group/test-codex-dataset.tar .

**Comment by jswelling** [comment]
Done by https://github.com/hubmapconsortium/ingest-pipeline/commit/c4edb1895a7032b5dd60ffa1d10359933e2dd7a7
