### ISSUE TITLE
Tracking issue for IMC / 3D IMC assay naming confusion

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/ingest-pipeline#338]
This affects a tranche of Florida TMC data including HBM387.XZWR.467

>  @Joel Welling @Chris Briggs Those new IMC datasets are 3D IMC (metadata schema: 
> https://hubmapconsortium.github.io/ingest-validation-tools/imc3d/) and I believe the previously published IMC datasets were
> 2D IMC (no z-stack, metadata schema: https://hubmapconsortium.github.io/ingest-validation-tools/imc/). I cannot distinguish
> the two types in the portal apart from inspecting the “assay type” field in the metadata, which says “Imaging Mass Cytometry”
> for previously published data and “3D Imaging Mass Cytometry” for the new datasets. Shouldn’t that be reflected in the assay
> type that we are using to index those datasets?

see  https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1623240123055400

**Comment by cebriggs7135** [comment]
@jswelling @ngehlenborg @mccalluc The assay_category for IMC (2D & 3D) should be "imaging" as it already is for the only IMC data published on the portal to date. Cytometry is not spectrometry so "imaging" is more fitting. Imaging was originally intended to refer to microscopy but it should be broadened to include IMC. Will discuss at June 11 portal call while Hunter (UFL) waits to see if he should upload a corrected metadata TSVs for these datasets.

**Comment by cebriggs7135** [comment]
@jswelling @ngehlenborg  @mccalluc  After lengthy discussion at the June 11, 2021 Portal call, the decision made was to leave the assay_category as is. A group dedicated to assay_categories will revisit this in the future but leave as is for processing the new 3D IMC datasets.

**Comment by khanshawPSC** [comment]
https://github.com/hubmapconsortium/ingest-pipeline/issues/345
Closed because of a duplicate.

**Comment by jswelling** [comment]
Resolved by https://github.com/hubmapconsortium/search-api/pull/349 pending merge
