### ISSUE TITLE
Tracking issue for 3D IMC wrong datatype

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/ingest-pipeline#339]
This issue applies to a tranche of Florida IMC/3DIMC datasets including HBM387.XZWR.467

From @ilan-gold :
> It seems the data they uploaded was Uint16 but the proper type should be Float
> from my understanding so I emailed Laura about this.  I had brought this up with
> them before but it looks like it was not resolved.

**Comment by ilan-gold** [comment]
Thanks for opening - I reached out to Laura so we should hear back overnight

**Comment by cebriggs7135** [comment]
@ilan-gold @jswelling After lengthy discussion at the June 11, 2021 Portal call, the decision made was to leave the assay_category as is. A group dedicated to assay_categories will revisit this in the future but leave as is for processing the new 3D IMC datasets.

**Comment by ilan-gold** [comment]
Ok I still haven't heard back from Laura so seems like that's still a blocker.  I believe everyone was copied on/has seen the email I sent.

**Comment by jswelling** [comment]
https://github.com/hubmapconsortium/portal-ui/issues/1914 is a better description of this same issue.
