### ISSUE TITLE
provide kwargs to ingest-validation-tests plugins

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/ingest-pipeline#347]
New plugin tests are being implemented that need auth_tok and/or the names of endpoints.  There is currently no way to pass that data from the Airflow environment down to the plugin.  Provide for passing kwargs down to the plugin.  This will involve changes to the places where ingest-validation-tools is invoked in Airflow and a PR against ingest-validation-tools to pass the kwargs down to the plugins.  And a PR against ingest-validation-tests to add the kwargs, maybe?

**Comment by jswelling** [comment]
Resolved by https://github.com/hubmapconsortium/ingest-pipeline/pull/356 (still in review)

**Comment by khanshawPSC** [comment]
Discussed this in stand-up this morning. Bill offered to review with Charles.

**Comment by jswelling** [comment]
See https://github.com/hubmapconsortium/ingest-pipeline/pull/356 which is currently pending review.
