### ISSUE TITLE
Tracking issue for Lightsheet wrong datatype

### ISSUE THREAD

**Issue by jswelling** [hubmapconsortium/ingest-pipeline#348]
The Florida Lightsheet datasets currently include ome.tiff files with datatype UInt8, but the associated Zeiss .czi files have datatype UInt16.  This implies a translation error was made in generating the .ome.tiff files from the .czi files.  This will require the TMC to re-upload the ome.tiff files.  Hunter Hakimian is working on this, per a Slack conversation June 15 2021.

**Comment by khanshawPSC** [comment]
Datasets were published
