### ISSUE TITLE
Deliver single CSV with all per-cell information from Globus

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-pipeline#39]
@jswelling : Creating an issue to mirror the [sprint doc](https://docs.google.com/document/d/1jnYwQZCaduJG2WczIVsDjbpTnoZpcIbB7l8A-RupzC8/edit#bookmark=id.4h31d8ukch0l) item:

Single file with cell ID | Joel, with Ted and Maria
-- | --

We want to have a single CSV with all the per-file data: This will start with what I understand to be the cytokit output, which had these columns in the example I was given:

<details>

- region_index
- tile_index
- tile_x
- tile_y
- rid
- rx
- ry
- id
- x
- y
- z
- cm:circularity
- cm:diameter
- cm:diameter_vx
- cm:perimeter
- cm:size
- cm:size_vx
- cm:solidity
- nm:circularity
- nm:diameter
- nm:diameter_vx
- nm:perimeter
- nm:size
- nm:size_vx
- nm:solidity
- cg:n_neighbors
- cg:neighbor_ids
- cg:adj_neighbor_pct
- cg:adj_bg_pct
- cb:on_border
- nb:on_border
- ci:DAPI-002:mean
- ci:CD31:mean
- ci:CD8:mean
- ci:CD45:mean
- ci:DAPI-003:mean
- ci:CD20:mean
- ci:Ki67:mean
- ci:CD3e:mean
- ci:DAPI-004:mean
- ci:Actin:mean
- ci:Podoplanin:mean
- ci:CD68:mean
- ci:DAPI-005:mean
- ci:PanCK:mean
- ci:CD21:mean
- ci:CD4:mean
- ci:DAPI-006:mean
- ci:EMPTY:mean
- ci:CD45RO:mean
- ci:CD11c:mean
- ci:DAPI-007:mean
- ci:EMPTY:mean.1
- ci:E_CAD:mean
- ci:CD107a:mean
- ci:DAPI-008:mean
- ci:EMPTY:mean.2
- ci:CD44:mean
- ci:HistoneH3:mean
- ni:DAPI-002:mean
- ni:CD31:mean
- ni:CD8:mean
- ni:CD45:mean
- ni:DAPI-003:mean
- ni:CD20:mean
- ni:Ki67:mean
- ni:CD3e:mean
- ni:DAPI-004:mean
- ni:Actin:mean
- ni:Podoplanin:mean
- ni:CD68:mean
- ni:DAPI-005:mean
- ni:PanCK:mean
- ni:CD21:mean
- ni:CD4:mean
- ni:DAPI-006:mean
- ni:EMPTY:mean
- ni:CD45RO:mean
- ni:CD11c:mean
- ni:DAPI-007:mean
- ni:EMPTY:mean.1
- ni:E_CAD:mean
- ni:CD107a:mean
- ni:DAPI-008:mean
- ni:EMPTY:mean.2
- ni:CD44:mean
- ni:HistoneH3:mean

</details>

... and will add columns for cell clusters coming from Ted. The sample files I was given only have a single column:
- R001_X001_Y001.ome.tiffcellmeans.csv
- R001_X001_Y001.ome.tiffclustermeansclustermeansbyallmasks
- R001_X001_Y001.ome.tiffclustermeansjustbycellmask

**Also**: For downstream processing to work, the next step in the pipeline needs to know what the filename output from this step will be. Please make it unique and descriptive.

When this is done, please ping @mccalluc so I can continue the work begun in https://github.com/hubmapconsortium/vitessce-data/pull/77 and carry it through to `portal-containers` and `airflow-dev`

**Comment by jswelling** [comment]
Verify that this is obsolete with @mccalluc , and if not obsolete clarify with @mruffalo

**Comment by mccalluc** [comment]
@ilan-gold : Looping you in since I haven't touched the vitessce-conf in forever. Is there still work that needs to be done, or have we moved on?

**Comment by ilan-gold** [comment]
I don't think anything here needs to be done from what I can tell.  We can reopen if needed.

**Comment by jswelling** [comment]
Closed after consultation by @mccalluc and @ilan-gold
