### ISSUE TITLE
Dockerized Airflow with dummy DAG for dev

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-pipeline#41]
Docker container that will run airflow with "Pipeline Integration" included.  We want a dummy pipeline that will wait a number of specified seconds perform the callbacks.  The dummy pipeline should trigger when the file dummy-pipeline.json is present containing the number of seconds to delay the initial callback, optionally an error message to simulate an error callback and also optionally a second time interval to simulate creating a derived dataset with the creation of a few files in the derived dataset.  It will send back standard file information for any files present in the dataset directory.  The assay/data type should be stored in the resulting dataset as "other"->"testing".

**Comment by jswelling** [comment]
The pipeline is actually 'other'->'devtest'.  There is only one time delay, in the secondary dataset pipeline, but it turns out that's the only logical place to put it (I thing).
