### ISSUE TITLE
Begin Airflow2.0 Migration

### ISSUE THREAD

**Issue by jpuerto-psc** [hubmapconsortium/ingest-pipeline#581]

**Comment by Daghis** [comment]
Personal test environments for exploring Airflow installation and upgrade have been set up.

1. Intel MacMini (personal equipment) set up with Ubuntu VM running puppetserver (unable to run on ARM)
2. M1 MacBook Pro set up with Fedora VM (free and comparable to RHEL) with puppet agent setup and have set up basic Airflow setup.

```
[root@fedora puppet]# puppet apply install.pp --verbose
Notice: Compiled catalog for fedora. in environment production in 0.23 seconds
Info: Using environment 'production'
Info: Applying configuration version '1655410604'
Notice: /Stage[main]/Main/Package[python3-devel]/ensure: created
Notice: /Stage[main]/Main/Package[apache-airflow]/ensure: created
Notice: Applied catalog in 7.22 seconds
```
