### ISSUE TITLE
Manifest of pointers to SPRM region information for visualization

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-pipeline#62]
Matt, Chuck, Nils: Please add details about what you want here. This would likely need to be created in the CWL workflow that CMU-TC provides.

**Comment by mccalluc** [comment]
@ilan-gold : This is an older issue - Are you getting the information you need, or does something still need to happen here?

**Comment by mccalluc** [comment]
@ilan-gold : Ping. Is this still relevant?

**Comment by ilan-gold** [comment]
I don't think so, although there is not a lot to go off of.

**Comment by jswelling** [comment]
Done.
