### ISSUE TITLE
Check all metadata.tsv fields with corresponding entities in HuBMAP Portal databases through entity-api and/or uuid-api

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-pipeline#67]
Ensure that values entered into fields in metadata.tsv are consistent with entities created during donor, organ, tissue, and dataset registration. At least check the following:

1. Any donor, organ, tissue, and dataset IDs used in metadata.tsv have a valid existing entry in Neo4j and MySQL (UUID) databases.
2. The relationships between donor, organ, tissue, and datasets specified in the metadata.tsv is consistent with relationships in Neo4j and MySQL

**Comment by jswelling** [comment]
What's actually being done is that:
- the sample must exist.
- the donor string must be the first substring of the sample string.  Since the sample string is generated automatically, this guarantees that the donor must exist.
