### ISSUE TITLE
Implement assay-specific QA/QC checks/measurements for 10x RNAseq and pass resulting information for display in Ingest UI and/or Portal UI as appropriate.

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-pipeline#69]
Specific list of community-standard QA/QC checks coming from Alex and Matt through work with data providers and assay teams.

Matt, Joel, Ivan: Implementation in pipelines and/or ingest validation.

**Comment by jswelling** [comment]
Needs discussion with @mruffalo .  Is this the live issue tracking this discussion?

**Comment by khanshawPSC** [comment]
Check with @mruffalo to see if he is doing any checking based on QA/QC or just measuring and reporting the results? Is there something else that is obvious we should be doing for QA/QC in terms of data?

**Comment by khanshawPSC** [comment]
Completed with FastQC then metric outputs
