### ISSUE TITLE
Define what is required for representing DAG provenance and derived data provenance in the Portal.

### ISSUE THREAD

**Issue by pdblood** [hubmapconsortium/ingest-pipeline#74]
DAG Provenance and getting more information about how data was processed [Nils]
Minimum deliverable:
having the ability to show what the inputs for a given workflow were and
having the ability of UI to generate links to visualization of CWL workflow used to generate outputs, e.g. https://view.commonwl.org/workflows/github.com/hubmapconsortium/codex-pipeline/blob/f3d6e97408b1c542641b313c1ea8d3115d72e3f8/pipeline.cwl 
Current examples of pipeline processing information
https://portal.test.hubmapconsortium.org/browse/dataset/9d23c5a1e485a6882a403b4800889147
https://portal.test.hubmapconsortium.org/browse/dataset/08c97eb2fedc6bf1cfb4c6c7a52a42a2 
Earlier discussion in #hive-developers: https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1588892046185800
we need paths within repo (filenames are ambiguous because same file can exist in two directories, e.g. “./workflow.cwl” and “./old/workflow.cwl”)
General concern: Github is not archival (repos can be renamed, deleted, etc.) and we should make sure to archive the referenced repos, e.g., in Zenodo, and reference those rather than the Github version.

**Comment by jswelling** [comment]
Closing this, as immediate-term goals have been met.
