### ISSUE TITLE
Deprecate the use of `hubmap_commons.type_client`

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-pipeline#837]
As we've deprecated the assay types yaml from search-api and moved to UBKG ontology-api, this [`hubmap_commons.type_client`](https://github.com/hubmapconsortium/commons/blob/main/hubmap_commons/type_client.py) module will be removed from commons. 

ingest-pipeline should deprecate the use of https://github.com/search?q=repo%3Ahubmapconsortium%2Fingest-pipeline+TypeClient&type=code make calls against UBKG ontology-api directly.

**Comment by yuanzhou** [comment]
@sunset666 We are getting very close to fully deprecate the `TypeClient` and we plan to remove this module from commons soon. Looks like it's still being referenced in the ingest-pipeline code: https://github.com/search?q=repo%3Ahubmapconsortium%2Fingest-pipeline+TypeClient&type=code

Can you confirm and remove the reference?

**Comment by sunset666** [comment]
Thank you @yuanzhou, we will be scheduling work to validate/remove any references for it.

**Comment by yuanzhou** [comment]
7/24/2024, got the word from @sunset666 that we can go ahead and remove the TypeClient from the commons.
